version: '3.1'
services:
  app:
    container_name: app-service-restaurant
    image: app-service-restaurant
    build: ./
    ports:
      - "8082:8082"
    depends_on:
      - dbpostgresql
  dbpostgresql:
    image: postgres
    ports:
      - "5444:5444"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=restaurant