apiVersion : apps/v1
kind: Deployment
metadata:
  name: servicerestaurant-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: servicerestaurant
  template:
    metadata:
      labels:
        app: servicerestaurant 
    spec:
      containers:
        - name: servicerestaurant 
          image: razvan426823wedeliver.azurecr.io/servicerestaurant
          imagePullPolicy: Always
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: SPRING
          ports:
          - containerPort: 8082
