apiVersion: v1
kind: Service
metadata:
    name: servicerestaurant-service
spec:
    type: LoadBalancer
    selector:
        app: servicerestaurant
    ports:
        - port: 80 
          targetPort: 8080
    
