# This is a basic workflow to help you get started with Actions

name: deploy-workflow

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-and-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # checkout the repo
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@master
        
    - name: 'Login to GitHub Container Registry'
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: razvan286
        password: ${{ secrets.RESTAURANT_DEPLOY_TOKEN }}
        
    - name: 'Build the service-restaurant image'
      run: |
        docker build . --tag ghcr.io/razvan286/service-restaurant:latest
        docker push ghcr.io/razvan286/service-restaurant:latest
